### ISSUE TITLE
Installation of laravel geoip in laravel 5.5.28

### ISSUE THREAD

**Issue by eaponiente** [Torann/laravel-geoip#99]
working fine in version of Laravel below 5.5 but when I install this package to the latest version of laravel this error shows up

PHP Version: 7.2.0
Laravel Version: 5.5.28

```
Using version ^1.0 for torann/geoip
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Warning:  Uncaught ErrorException: require(/home/vagrant/Code/betting/trunk/vendor/composer/../torann/geoip/src/helpers.php): failed to open stream: No such file or directory in /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php:66
Stack trace:
#0 /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/home/v...', '/home/vagrant/C...', 66, Array)
#1 /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php(66): require()
#2 /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php(56): composerRequiree055b4b47eb01188bb4f774b3b3aa3d6('1e298922c3e2134...', '/home/vagrant/C...')
#3 /home/vagrant/Code/betting/trunk/vendor/autoload.php(7): ComposerAutoloaderInite055b4b47eb01188bb4f774b3b3aa3d6::getLoader()
#4 /home/vagrant/Code/betting/trunk/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/home/vagrant/C...')
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher in /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php on line 66

Warning: Uncaught ErrorException: require(/home/vagrant/Code/betting/trunk/vendor/composer/../torann/geoip/src/helpers.php): failed to open stream: No such file or directory in /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php:66
Stack trace:
#0 /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/home/v...', '/home/vagrant/C...', 66, Array)
#1 /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php(66): require()
#2 /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php(56): composerRequiree055b4b47eb01188bb4f774b3b3aa3d6('1e298922c3e2134...', '/home/vagrant/C...')
#3 /home/vagrant/Code/betting/trunk/vendor/autoload.php(7): ComposerAutoloaderInite055b4b47eb01188bb4f774b3b3aa3d6::getLoader()
#4 /home/vagrant/Code/betting/trunk/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/home/vagrant/C...')
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher in /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  composerRequiree055b4b47eb01188bb4f774b3b3aa3d6(): Failed opening required '/home/vagrant/Code/betting/trunk/vendor/composer/../torann/geoip/src/helpers.php' (include_path='.:/usr/share/php') in /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php on line 66

Fatal error: composerRequiree055b4b47eb01188bb4f774b3b3aa3d6(): Failed opening required '/home/vagrant/Code/betting/trunk/vendor/composer/../torann/geoip/src/helpers.php' (include_path='.:/usr/share/php') in /home/vagrant/Code/betting/trunk/vendor/composer/autoload_real.php on line 66
```

**Comment by Torann** [comment]
This was fixed a while back
